# Generated by Django 4.2.2 on 2023-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rB', models.IntegerField(default=0)),
                ('client_dice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_rA', models.IntegerField(default=0)),
                ('server_result', models.IntegerField(default=0)),
                ('server_dice', models.IntegerField(default=0)),
            ],
        ),
    ]
