# Generated by Django 4.2.2 on 2023-06-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diceApp', '0002_rename_server_result_server_server_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_string',
            field=models.IntegerField(default=0),
        ),
    ]
